// S27.8 — Round-trip integration test: validates that JSON v0.2 fixture
// generated by backend (sinpapel_export_flujo --inline-catalogs) parses
// correctly via parseV0_2, re-serializes to schema-equivalent shape, and
// preserves all fields field-by-field.
//
// Fixture generated by scripts/round-trip-e2e.sh (en creditos repo).
// Regenerate after any schema change en sinpapel/schemas/flujo_export.py.

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import {
  parseV0_2,
  serializeV0_2,
  validateSchema,
} from '../src/data/schema-v0_2.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const fixturePath = join(__dirname, 'fixtures/round-trip-v0_2.json')
const fixture = JSON.parse(readFileSync(fixturePath, 'utf-8'))

describe('round-trip v0.2 con backend-generated fixture', () => {
  it('fixture valida contra validateSchema (no throw)', () => {
    expect(() => validateSchema(fixture)).not.toThrow()
    expect(fixture.schema_version).toBe('0.2')
  })

  it('parseV0_2 hidrata state shape con counts correctos', () => {
    const state = parseV0_2(fixture)
    expect(state.flujo.nombre).toBe(fixture.flujo.nombre)
    expect(state.estados.length).toBe(fixture.catalogos.estados.length)
    expect(state.etapas.length).toBe(fixture.catalogos.etapas.length)
    expect(state.grupos.length).toBe(fixture.catalogos.grupos.length)
    expect(state.tipos_documento.length).toBe(fixture.catalogos.tipos_documento.length)
    expect(state.transiciones.length).toBe(fixture.flujo.transiciones.length)
    expect(state.requisitos.length).toBe(fixture.flujo.requisitos.length)
  })

  it('Estado.etapa relation preserved (nombre ref)', () => {
    const state = parseV0_2(fixture)
    // Find estado con etapa (RT_CAPTURA has etapa=RT_PreAprobacion en fixture)
    const estadoConEtapa = state.estados.find((e) => e.etapa)
    expect(estadoConEtapa).toBeDefined()
    expect(typeof estadoConEtapa.etapa).toBe('string')
    // Etapa referenced existe en state.etapas
    expect(state.etapas.find((et) => et.nombre === estadoConEtapa.etapa)).toBeDefined()
  })

  it('positions migration nombre <-> id consistent', () => {
    const state = parseV0_2(fixture)
    const positions = state.flujo.metadatos.positions
    // Internal state has id-keyed positions (nombre -> id via _hashId)
    const idKeys = Object.keys(positions)
    expect(idKeys.length).toBe(Object.keys(fixture.flujo.metadatos.positions).length)
    // Verify each position has x/y
    for (const id of idKeys) {
      expect(positions[id]).toHaveProperty('x')
      expect(positions[id]).toHaveProperty('y')
    }
  })

  it('re-serialize produce schema-equivalent shape (round-trip)', () => {
    const state = parseV0_2(fixture)
    const reExported = serializeV0_2(state)
    expect(reExported.schema_version).toBe('0.2')

    // Catalogs counts preserved
    expect(reExported.catalogos.estados.length).toBe(fixture.catalogos.estados.length)
    expect(reExported.catalogos.etapas.length).toBe(fixture.catalogos.etapas.length)
    expect(reExported.catalogos.grupos.length).toBe(fixture.catalogos.grupos.length)
    expect(reExported.catalogos.tipos_documento.length).toBe(fixture.catalogos.tipos_documento.length)

    // Estados nombre set preserved
    expect(
      reExported.catalogos.estados.map((e) => e.nombre).sort()
    ).toEqual(
      fixture.catalogos.estados.map((e) => e.nombre).sort()
    )

    // Grupos preservadas
    expect(reExported.catalogos.grupos.map((g) => g.name).sort()).toEqual(
      fixture.catalogos.grupos.map((g) => g.name).sort()
    )

    // Transiciones byte-equal (sorted grupos en serializer)
    expect(reExported.flujo.transiciones).toEqual(fixture.flujo.transiciones)

    // Requisitos byte-equal
    expect(reExported.flujo.requisitos).toEqual(fixture.flujo.requisitos)

    // Positions name-keyed both sides (round-trip preserves)
    expect(reExported.flujo.metadatos.positions).toEqual(
      fixture.flujo.metadatos.positions,
    )
  })

  it('data preservation matrix — Estado fields field-by-field', () => {
    const state = parseV0_2(fixture)
    const reExported = serializeV0_2(state)
    fixture.catalogos.estados.forEach((origEstado) => {
      const reEstado = reExported.catalogos.estados.find(
        (e) => e.nombre === origEstado.nombre,
      )
      expect(reEstado).toBeDefined()
      expect(reEstado.color).toBe(origEstado.color)
      expect(reEstado.icono).toBe(origEstado.icono)
      expect(reEstado.descripcion).toBe(origEstado.descripcion)
      expect(reEstado.orden).toBe(origEstado.orden)
      expect(reEstado.activo).toBe(origEstado.activo)
      expect(reEstado.etapa).toBe(origEstado.etapa)
      expect(reEstado.permite_expediente).toBe(origEstado.permite_expediente)
      expect(reEstado.expediente_obligatorio).toBe(origEstado.expediente_obligatorio)
    })
  })
})
